// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dal

var TableNames = struct {
	Favorite          string
	Landing           string
	Lot               string
	LotCanceledReason string
	LotFile           string
	LotTopic          string
	Payment           string
	Post              string
	Review            string
	Settings          string
	Topic             string
	User              string
	Views             string
}{
	Favorite:          "favorite",
	Landing:           "landing",
	Lot:               "lot",
	LotCanceledReason: "lot_canceled_reason",
	LotFile:           "lot_file",
	LotTopic:          "lot_topic",
	Payment:           "payment",
	Post:              "post",
	Review:            "review",
	Settings:          "settings",
	Topic:             "topic",
	User:              "user",
	Views:             "views",
}
