// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dal

var TableNames = struct {
	Lot      string
	LotTopic string
	Topic    string
	User     string
}{
	Lot:      "lot",
	LotTopic: "lot_topic",
	Topic:    "topic",
	User:     "user",
}
