linters-settings:
  goimports:
    local-prefixies: github.com/bots-house/birzzha

output:
  format: tab

run:
  skip-dirs:
    - api/gen
    - store/postgres/dal
  
  
linters:
  enable:
    - misspell
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - unconvert
    - megacheck
    - gas
    - dupl
    - unparam
    - bodyclose
    - gosec
    - goconst
    - gofmt
    - goimports
    - prealloc
    - scopelint
    - gocritic
    - goprintffuncname
    - rowserrcheck
    - scopelint
    - stylecheck
    - gocyclo
    # - wsl
    # - interfacer
    # - gomnd
    # - goerr113
    # - maligned
    # - nestif
