version: "3.0"

volumes:
  postgres:
  redis:

services:
  postgres:
    image: postgres:12

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: brz
      POSTGRES_PASSWORD: brz
      POSTGRES_DB: brz

    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    ports:
      - 6379:6379
