pkgname = "dal"
output = "store/postgres/dal"
no-tests = true
no-hooks = true
no-auto-timestamps = true

wipe = true

[psql]
  dbname = "brz"
  host   = "localhost"
  port   = 5432
  user   = "brz"
  pass   = "brz"
  sslmode = "disable"
  blacklist = [
    "schema_migrations"
  ]
