name: Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to docker.pkg.github.com
        run:  echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull latest Docker image
        run: docker pull docker.pkg.github.com/${{ github.repository }}/birzzha:latest || true

      - name: Build the Docker image
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/birzzha:latest -t docker.pkg.github.com/${{ github.repository }}/birzzha:$(git rev-parse --short=4 ${{ github.sha }}) .

      - name: Push image to GitHub Packages
        run: docker push docker.pkg.github.com/${{ github.repository }}/birzzha