name: Deploy Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to docker.pkg.github.com
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull latest Docker image for cache
        run: |
          docker pull docker.pkg.github.com/${{ github.repository }}/birzzha:staging || true

      - name: Build the Docker image
        run: |
          docker build \
            --build-arg REVISION=${GITHUB_SHA::8} \
            --cache-from docker.pkg.github.com/${{ github.repository }}/birzzha:staging \
            --tag docker.pkg.github.com/${{ github.repository }}/birzzha:staging \
            .

      - name: Push image to GitHub Packages
        run: |
          docker push \
            docker.pkg.github.com/${{ github.repository }}/birzzha:staging