name: Deploy Production

on:
  release:
    types:
     - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to docker.pkg.github.com
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull latest Docker image for cache
        run: |
          docker pull docker.pkg.github.com/${{ github.repository }}/birzzha:staging || true
          docker pull docker.pkg.github.com/${{ github.repository }}/birzzha:latest || true

      - name: Build the Docker image
        run: |
          docker build \
            --build-arg REVISION=${GITHUB_REF##*/} \
            --cache-from docker.pkg.github.com/${{ github.repository }}/birzzha:staging \
            --cache-from docker.pkg.github.com/${{ github.repository }}/birzzha:latest \
            --tag docker.pkg.github.com/${{ github.repository }}/birzzha:latest \
            --tag docker.pkg.github.com/${{ github.repository }}/birzzha:${GITHUB_REF##*/} \
            .

      - name: Push image to GitHub Packages
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/birzzha:latest
          docker push docker.pkg.github.com/${{ github.repository }}/birzzha:${GITHUB_REF##*/}

      - name: Call Deploy Hooks
        run: |
          .github/deploy.sh ${{ secrets.DEPLOY_HOOKS }}